src/Entity/CustomerInterface.php
<?php

namespace App\Entity;

use DateTimeInterface;

interface CustomerInterface
{
    /**
     * @return string|null
     */
    public function getShippingAddress(): ?string;

    /**
     * @return DateTimeInterface|null
     */
    public function getBirthDate(): ?DateTimeInterface;

    /**
     * @return OrderInterface[]
     */
    public function getOrders(): array;
}

src/Entity/OrderInterface.php
<?php

namespace App\Entity;

use DateTimeInterface;

interface OrderInterface
{
    public function getOrderDate(): ?DateTimeInterface;
    public function getDeliveryDate(): ?DateTimeInterface;
    public function getOrderStatus(): string;
    public function getTotalAmount(): float;
    public function getCustomer(): ?CustomerInterface;
    public function getOrderItems(): array;
    /**
     * @todo Implémenter une méthode getPayment() qui retourne un objet de type PaymentInterface
     */
//    public function getPayment();
}

src/Entity/UserInterface.php
<?php

namespace App\Entity;

interface UserInterface
{
    /**
     * @return string|null
     */
    public function getFirstName(): ?string;

    /**
     * @return string|null
     */
    public function getLastName(): ?string;

    /**
     * @return string|null
     */
    public function getEmail(): ?string;

    /**
     * @return string|null
     */
    public function getAddress(): ?string;

    /**
     * @return string|null
     */
    public function getPhone(): ?string;
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Customer;
use App\Entity\Product;
use App\Form\RegistrationForm\CheckoutRegistrationFormType;
use App\Form\UserForm\DynamicUserFormType;
use App\Manager\CartManager;
use App\Service\Form\FormProcessor;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\UserAuthenticatorInterface;
use App\Security\UserAuthenticator;

#[Route('/panier', name: 'app_cart')]
class CartController extends AbstractController
{
    /**
     * @var CartManager
     */
    private CartManager $cartManager;
    /**
     * @var FormProcessor
     */
    private FormProcessor $formProcessor;

    /**
     * @param CartManager $cartManager
     * @param FormProcessor $formProcessor
     */
    public function __construct(CartManager $cartManager, FormProcessor $formProcessor)
    {
        $this->cartManager = $cartManager;
        $this->formProcessor = $formProcessor;
    }

    /**
     * @param Request $request
     * @param UserAuthenticatorInterface $userAuthenticator
     * @param UserAuthenticator $authenticator
     * @return Response
     */
    #[Route('/', name: '_index')]
    public function index(Request $request, UserAuthenticatorInterface $userAuthenticator, UserAuthenticator $authenticator): Response
    {
        if ($this->getUser() && $this->isGranted('ROLE_SELLER')) {
            return $this->redirectToRoute('app_home');
        }

        $cart = $this->cartManager->getCurrentCart();

        if ($this->getUser() && $cart->getCustomer() !== $this->getUser()) {
            $cart->setCustomer($this->getUser());
            $this->cartManager->saveCart($cart);
        }

        $form = $this->getUser() ?
            $this->formProcessor->create(DynamicUserFormType::class, $this->getUser(), ['notBirthDate' => true, 'notEmail' => true])
            : $this->formProcessor->create(CheckoutRegistrationFormType::class, new Customer());

        if ($this->formProcessor->process($request, $form)) {
            if (!$this->getUser()) {
                $user = $form->getData();
                $userAuthenticator->authenticateUser(
                    $user,
                    $authenticator,
                    $request
                );
            }

            return $this->redirectToRoute('app_payment_index');
        }

        $this->cartManager->saveCart($cart);

        return $this->render('cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView()
        ]);
    }

    /**
     * @param Request $request
     * @param Product $product
     * @return JsonResponse
     */
    #[Route('/ajouter/{id}', name: '_add', methods: ['POST'])]
    public function add(Request $request, Product $product): JsonResponse
    {
        if ($this->getUser() && !$this->isGranted("ROLE_CUSTOMER")) {
            return $this->json([
                'status' => "error",
                'message' => 'Vous devez être connecté en tant que client pour ajouter un produit au panier'
            ], 403);
        }

        $token = $request->headers->get('X-CSRF-TOKEN');

        if (!$this->isCsrfTokenValid('add-item', $token)) {
            return $this->json([
                'status' => "error",
                'message' => 'Le token est invalide'
            ], 400);
        }

        $quantity = json_decode($request->getContent(), true)['quantity'];

        $orderItem = $this->cartManager->getCartFactory()->createItem($product, $quantity);
        $orderItemSeller = $this->cartManager->getCartFactory()->createItemSeller($product);

        $cart = $this->cartManager->getCurrentCart();

        $cart->addOrderItem($orderItem)
            ->addOrderItemSeller($orderItemSeller)
            ->setCustomer($this->getUser());

        $this->cartManager->saveCart($cart);

        return $this->json([
            'status' => 'success',
            'message' => 'Le produit a bien été ajouté',
            'total' => $orderItem->getTotal()
        ]);
    }

    /**
     * @param Request $request
     * @param Product $product
     * @return JsonResponse
     */
    #[Route('/modifier/{id}', name: '_update', methods: ['PUT'])]
    public function update(Request $request, Product $product): JsonResponse
    {
        $token = $request->headers->get('X-CSRF-TOKEN');

        if ($this->isCsrfTokenValid('update-item', $token) === false) {
            return $this->json([
                'status' => "error",
                'message' => 'Le token est invalide'
            ], 400);
        }

        $quantity = json_decode($request->getContent(), true)['quantity'];

        $orderItem = $this->cartManager->getOrderItemByProduct($product);

        if ($orderItem === null) {
            return $this->json([
                'status' => "error",
                'message' => 'Le produit n\'existe pas dans le panier'
            ], 400);
        }

        $orderItem->setQuantity($quantity);


        $this->cartManager->saveCart($this->cartManager->getCurrentCart());

        return $this->json([
            'status' => 'success',
            'message' => 'Le produit a bien été modifié',
            'total' => $orderItem->getTotal()
        ]);
    }

    /**
     * @param Request $request
     * @param Product $product
     * @return JsonResponse
     */
    #[Route('/supprimer/{id}', name: '_remove', methods: ['DELETE'])]
    public function remove(Request $request, Product $product): JsonResponse
    {
        $token = $request->headers->get('X-CSRF-TOKEN');

        if ($this->isCsrfTokenValid('remove-item', $token) === false) {
            return $this->json([
                'status' => "error",
                'message' => 'Le token est invalide'
            ], 400);
        }

        $cartItem = $this->cartManager->getOrderItemByProduct($product);
        $cartItemSeller = $this->cartManager->getOrderItemSellerBySeller($product->getSeller());

        if ($cartItem === null) {
            return $this->json([
                'status' => "error",
                'message' => 'Le produit n\'existe pas dans le panier'
            ], 400);
        }

        $cart = $this->cartManager->getCurrentCart();
        $cart->removeOrderItem($cartItem)
            ->removeOrderItemSeller($cartItemSeller);

        $this->cartManager->saveCart($cart);

        return $this->json([
            'status' => 'success',
            'message' => 'Le produit a bien été supprimé'
        ]);
    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    #[Route('/vider', name: '_clear', methods: ['DELETE'])]
    public function clear(Request $request): JsonResponse
    {
        $token = $request->headers->get('X-CSRF-TOKEN');

        if ($this->isCsrfTokenValid('clear-cart', $token) === false) {
            return $this->json([
                'status' => "error",
                'message' => 'Le token est invalide'
            ], 400);
        }

        $cart = $this->cartManager->getCurrentCart();
        $cart->removeOrderItems()
            ->removeOrderItemSellers();

        $this->cartManager->saveCart($cart);

        return $this->json([
            'status' => 'success',
            'message' => 'Le panier a bien été vidé'
        ]);
    }
}

templates/cart/_billing_form.html.twig
<div class="cart-page-billing-form">
    <h2>Informations de facturation</h2>
    <div class="billing-form-row">
        <div class="billing-form-row-item">
            {{ form_label(form.lastname) }}
            {{ form_widget(form.lastname) }}
            {% for error in form.lastname.vars.errors %}
                <span class="billing-form-row-item-error">{{ error.message }}</span>
            {% endfor %}
        </div>
        <div class="billing-form-row-item">
            {{ form_label(form.firstname) }}
            {{ form_widget(form.firstname) }}
            {% for error in form.firstname.vars.errors %}
                <span class="billing-form-row-item-error">{{ error.message }}</span>
            {% endfor %}
        </div>
    </div>
    <div class="billing-form-row">
        <div class="billing-form-row-item">
            {{ form_label(form.city) }}
            {{ form_widget(form.city) }}
            {% for error in form.city.vars.errors %}
                <span class="billing-form-row-item-error">{{ error.message }}</span>
            {% endfor %}
        </div>
        <div class="billing-form-row-item">
            {{ form_label(form.postalCode) }}
            {{ form_widget(form.postalCode) }}
            {% for error in form.postalCode.vars.errors %}
                <span class="billing-form-row-item-error">{{ error.message }}</span>
            {% endfor %}
        </div>
    </div>
    <div class="billing-form-row">
        <div class="billing-form-row-item">
            {{ form_label(form.streetNumber) }}
            {{ form_widget(form.streetNumber) }}
            {% for error in form.streetNumber.vars.errors %}
                <span class="billing-form-row-item-error">{{ error.message }}</span>
            {% endfor %}
        </div>
        <div class="billing-form-row-item">
            {{ form_label(form.street) }}
            {{ form_widget(form.street) }}
            {% for error in form.street.vars.errors %}
                <span class="billing-form-row-item-error">{{ error.message }}</span>
            {% endfor %}
        </div>
    </div>
    <div class="billing-form-row">
        <div class="billing-form-row-item">
            {{ form_label(form.phone) }}
            {{ form_widget(form.phone) }}
            {% for error in form.phone.vars.errors %}
                <span class="billing-form-row-item-error">{{ error.message }}</span>
            {% endfor %}
        </div>
    </div>
    <div class="billing-form-row">
        {% if form.email is defined %}
            <div class="billing-form-row-item">
                {{ form_label(form.email) }}
                {{ form_widget(form.email) }}
                {% for error in form.email.vars.errors %}
                    <span class="billing-form-row-item-error">{{ error.message }}</span>
                {% endfor %}
            </div>
        {% endif %}
        {% if form.password is defined %}
            <div class="billing-form-row-item">
                {{ form_label(form.password) }}
                {{ form_widget(form.password) }}
                {% for error in form.password.vars.errors %}
                    <span class="billing-form-row-item-error">{{ error.message }}</span>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="billing-form-row">
        {% if form.agreeTerms is defined %}
            <div class="billing-form-row-item">
                {{ form_widget(form.agreeTerms) }}
                {{ form_label(form.agreeTerms) }}
                {% for error in form.agreeTerms.vars.errors %}
                    <span class="billing-form-row-item-error">{{ error.message }}</span>
                {% endfor %}
            </div>
        {% endif %}
        {% if app.user is null %}
            <div class="billing-form-row-item">
                <a href="{{ path('app_login') }}">Déjà un compte ? Se
                    connecter</a>
            </div>
        {% endif %}
    </div>
</div>

templates/cart/_cart.html.twig
<section class="cart-page-cart">
    <h1>Mon panier</h1>
    <div class="cart-page-cart-items">
        {% if cart.orderItems|length == 0 %}
            <p class="cart-page-empty-cart">Votre panier est vide</p>
        {% endif %}
        <ul class="cart-items-list">
            {% for orderItem in cart.orderItems %}
                {% set updateCsrfToken = csrf_token('update-item') %}
                {% set removeCsrfToken = csrf_token('remove-item') %}
                <li class="cart-item">
                    <img src="{{ orderItem.product.pictures[0].path }}"
                         alt="{{ orderItem.product.pictures[0].alt }}"
                         class="cart-item-image">
                    <p class="cart-item-name">{{ orderItem.product.name }}</p>
                    <div class="cart-item-price">
                        {% if orderItem.product.discount %}
                            <p class="cart-item-price-old">{{ orderItem.product.price|number_format(2, ",") }}
                                €</p>
                            <p class="cart-item-price-new">{{ orderItem.product.getPriceWithDiscount|number_format(2, ",") }}
                                €</p>
                        {% else %}
                            <p class="cart-item-price-new">{{ orderItem.product.price|number_format(2, ",") }}
                                €</p>
                        {% endif %}
                    </div>
                    <div class="cart-item-quantity">
                        <label for="quantity">
                                        <span class="cart-page-quantity quantity-minus"
                                              data-product-id="{{ orderItem.product.id }}"
                                              data-quantity="1"
                                              data-url="{{ path('app_cart_update', {'id': orderItem.product.id}) }}"
                                              data-price="{{ orderItem.product.getPriceWithDiscount }}"
                                              data-token="{{ updateCsrfToken }}">
                                            <i class="fas fa-minus"></i>
                                        </span>
                            <input id="quantity" type="number" value="{{ orderItem.quantity }}" min="1"
                                   data-product-id="{{ orderItem.product.id }}"
                                   max="10" name="cart-page-quantity">
                            <span class="cart-page-quantity quantity-plus"
                                  data-quantity="1"
                                  data-product-id="{{ orderItem.product.id }}"
                                  data-url="{{ path('app_cart_update', {'id': orderItem.product.id}) }}"
                                  data-price="{{ orderItem.product.getPriceWithDiscount }}"
                                  data-token="{{ updateCsrfToken }}">
                                            <i class="fas fa-plus"></i>
                                        </span>
                        </label>
                    </div>
                    <div class="cart-item-total">
                        <p>{{ orderItem.getTotal|number_format(2, ",") }} €</p>
                    </div>
                    <div class="cart-item-remove">
                        <button class="cart-item-remove-button button button-red"
                                data-url="{{ path('app_cart_remove', {'id': orderItem.product.id} ) }}"
                                data-token="{{ removeCsrfToken }}">Supprimer
                        </button>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="cart-page-buttons">
        <a href="{{ path('app_home') }}" class="button button-blue">Continuer mes achats</a>
        {% if cart.orderItems|length > 0 %}
            <button class="cart-page-clear-cart-button button button-red"
                    data-url="{{ path('app_cart_clear') }}" data-token="{{ csrf_token('clear-cart') }}">
                Vider mon panier
            </button>
        {% endif %}
    </div>
</section>

templates/cart/_checkout.html.twig
    <div class="cart-page-checkout-info">
        <h2>Récapitulatif de la commande</h2>
        {% if app.user and app.user.shippingAddress %}
            <div class="cart-page-checkout-delivery">
                <p class="cart-page-checkout-delivery-title">Adresse de livraison</p>
                <p class="cart-page-checkout-delivery-address">{{ app.user.shippingAddress }}</p>
            </div>
        {% endif %}
        <div class="cart-page-checkout-subtotal">
            <p>Sous-total</p>
            <p class="cart-checkout-subtotal">{{ cart.total|number_format(2, ",") }} €</p>
        </div>
        <div class="cart-page-checkout-shipping-fees">
            <p>Frais de livraison</p>
            <p>Gratuit</p>
        </div>
        <div class="cart-page-checkout-total">
            <p>Total</p>
            <p class="cart-checkout-total">{{ cart.total|number_format(2, ",") }} €</p>
        </div>
        <div class="cart-page-checkout-buttons">
            {% if cart.orderItems|length > 0 %}
                <button type="submit" class="cart-page-checkout-button button button-red">Payer</button>
            {% endif %}
        </div>
    </div>

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon panier{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('cartPage') }}
{% endblock %}

{% block body %}

    <div class="cart-page-section">
            {{ include('cart/_cart.html.twig') }}
            {% if cart.orderItems|length > 0 %}
                {{ form_start(form, {'attr': {'class': 'cart-page-container-checkout'}}) }}
                {{ include('cart/_billing_form.html.twig') }}
                {{ include('cart/_checkout.html.twig') }}
                {{ form_end(form) }}
            {% endif %}
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('cartPage') }}
{% endblock %}