src/Entity/OrderInterface.php
<?php

namespace App\Entity;

use DateTimeInterface;

interface OrderInterface
{
    public function getOrderDate(): ?DateTimeInterface;
    public function getDeliveryDate(): ?DateTimeInterface;
    public function getOrderStatus(): string;
    public function getTotalAmount(): float;
    public function getCustomer(): ?CustomerInterface;
    public function getOrderItems(): array;
    /**
     * @todo Implémenter une méthode getPayment() qui retourne un objet de type PaymentInterface
     */
//    public function getPayment();
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Annotation\SlugProperty;
use App\Repository\ProductRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @SlugProperty(property="name")
 */
#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product extends AbstractEntity
{
    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\NotBlank(message: 'Veuillez saisir le nom du produit')]
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Le nom du produit doit contenir au moins {{ limit }} caractères',
        maxMessage: 'Le nom du produit doit contenir au maximum {{ limit }} caractères',
    )]
    #[Groups(['product:list'])]
    private string $name = '';

    /**
     * @var string
     */
    #[ORM\Column(type: 'text')]
    #[Assert\NotBlank(message: 'Veuillez saisir la description du produit')]
    private string $description = '';

    /**
     * @var float
     */
    #[ORM\Column(type: 'float')]
    #[Assert\NotBlank(message: 'Veuillez saisir le prix du produit')]
    #[Assert\Positive(message: 'Le prix du produit doit être positif')]
    #[Groups(['product:list'])]
    private float $price = 0.0;

    /**
     * @var int
     */
    #[ORM\Column(type: 'integer')]
    #[Assert\NotBlank(message: 'Veuillez saisir la quantité du produit')]
    #[Assert\Positive(message: 'La quantité du produit doit être positive')]
    #[Groups(['product:list'])]
    private int $quantity = 0;


    /**
     * @var Seller|null
     */
    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Seller $seller = null;

    /**
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OrderItem::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection|ArrayCollection $orderItems;
    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Picture::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection|ArrayCollection $pictures;

    /**
     * @var int|null
     */
    #[ORM\Column(nullable: true)]
    #[Assert\Positive(message: 'Le pourcentage de réduction doit être positif')]
    #[Groups(['product:list'])]
    private ?int $discount = null;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\ManyToMany(targetEntity: Caracteristic::class, inversedBy: 'products')]
    private Collection|ArrayCollection $caracteristics;

    /**
     * @var float|null
     */
    #[ORM\Column(nullable: true)]
    private ?float $shippingFee = null;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\ManyToMany(targetEntity: Category::class, mappedBy: 'products',cascade: ['persist'])]
    private Collection|ArrayCollection $categories;

    /**
     * @var Brand|null
     */
    #[ORM\ManyToOne(targetEntity: Brand::class, cascade: ['persist'], inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Brand $brand = null;


    public function __construct()
    {
        parent::__construct();
        $this->updatedAt = new DateTime();
        $this->categories = new ArrayCollection();
        $this->orderItems = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->caracteristics = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Product
     */
    public function setName(string $name): Product
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Product
     */
    public function setDescription(string $description): Product
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return float
     */
    public function getPrice(): float
    {
        return $this->price;
    }

    /**
     * @param float $price
     * @return Product
     */
    public function setPrice(float $price): Product
    {
        $this->price = round($price, 2);
        return $this;
    }

    /**
     * @return int
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * @param int $quantity
     * @return Product
     */
    public function setQuantity(int $quantity): Product
    {
        $this->quantity = $quantity;
        return $this;
    }

    /**
     * @param int $quantity
     * @return Product
     */
    public function addQuantity(int $quantity): Product
    {
        $this->quantity += $quantity;
        return $this;
    }

    /**
     * @return Seller|null
     */
    public function getSeller(): ?Seller
    {
        return $this->seller;
    }

    /**
     * @param Seller|null $seller
     * @return $this
     */
    public function setSeller(?Seller $seller): self
    {
        $this->seller = $seller;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param string $slug
     * @return $this
     */
    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    /**
     * @param OrderItem $orderItem
     * @return $this
     */
    public function addOrderItem(OrderItem $orderItem): self
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setProduct($this);
        }

        return $this;
    }

    /**
     * @param OrderItem $orderItem
     * @return $this
     */
    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getProduct() === $this) {
                $orderItem->setProduct(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    /**
     * @param Picture $picture
     * @return $this
     */
    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setProduct($this);
        }

        return $this;
    }

    /**
     * @param Collection $pictures
     * @return $this
     */
    public function setPictures(Collection $pictures): self
    {
        foreach ($pictures as $picture) {
            $this->addPicture($picture);
        }
        return $this;
    }

    /**
     * @param Picture $picture
     * @return $this
     */
    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProduct() === $this) {
                $picture->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return int|null
     */
    public function getDiscount(): ?int
    {
        return $this->discount;
    }

    /**
     * @param int|null $discount
     * @return $this
     */
    public function setDiscount(?int $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    /**
     * @return Collection<int, Caracteristic>
     */
    public function getCaracteristics(): Collection
    {
        return $this->caracteristics;
    }

    /**
     * @param Caracteristic $caracteristic
     * @return $this
     */
    public function addCaracteristic(Caracteristic $caracteristic): self
    {
        if (!$this->caracteristics->contains($caracteristic)) {
            $this->caracteristics->add($caracteristic);
        }

        return $this;
    }

    /**
     * @param Caracteristic $caracteristic
     * @return $this
     */
    public function removeCaracteristic(Caracteristic $caracteristic): self
    {
        $this->caracteristics->removeElement($caracteristic);

        return $this;
    }

    /**
     * @return float
     */
    public function getPriceWithDiscount(): float
    {
        if ($this->discount === null) {
            return $this->price;
        }
        $newPrice = $this->price - ($this->price * $this->discount / 100);
        return round($newPrice, 2);
    }

    /**
     * @return float|null
     */
    public function getShippingFee(): ?float
    {
        return $this->shippingFee;
    }

    /**
     * @param float $shippingFee
     * @return $this
     */
    public function setShippingFee(float $shippingFee): self
    {
        $this->shippingFee = $shippingFee;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    /**
     * @param Category $category
     * @return $this
     */
    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->addProduct($this);
        }

        return $this;
    }

    /**
     * @param Category $category
     * @return $this

src/Controller/Seller/MainController.php
<?php

namespace App\Controller\Seller;

use App\Service\Order\OrderService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_SELLER')]
#[Route('/ma-boutique', name: 'app_seller')]
class MainController extends AbstractController
{
    /**
     * @var OrderService
     */
    private OrderService $orderService;

    /**
     * @param OrderService $orderService
     */
    public function __construct(OrderService $orderService)
    {
        $this->orderService = $orderService;
    }

    /**
     * @return Response
     */
    #[Route('/', name: '_index')]
    public function index(): Response
    {
        $orders = $this->orderService->getOrdersForSeller($this->getUser());
        $incomesChart = $this->orderService->getTotalIncomesPerMonthChart($this->getUser(), $orders);

        $ordersChart = $this->orderService->getTotalOrdersPerMonthChart($orders);

        $productPerParentCategoryChart = $this->orderService->getTotalProductSoldPerCategoriesChart($this->getUser(), $orders, true);

        $productPerCategoryChart = $this->orderService->getTotalProductSoldPerCategoriesChart($this->getUser(), $orders, false);

        $topProductsChart = $this->orderService->getTotalTopProductsSoldChart($this->getUser(), $orders);

        $cartAverageChart = $this->orderService->getCartAveragePerMonthChart($this->getUser(), $orders);


        return $this->render('seller/main/index.html.twig', [
            'incomesChart' => $incomesChart,
            'ordersChart' => $ordersChart,
            'productPerParentCategoryChart' => $productPerParentCategoryChart,
            'productPerCategoryChart' => $productPerCategoryChart,
            'topProductsChart' => $topProductsChart,
            'cartAverageChart' => $cartAverageChart,
        ]);
    }
}

src/Controller/Seller/OrderController.php
<?php

namespace App\Controller\Seller;

use App\Entity\Order;
use App\Entity\OrderItemSeller;
use App\Entity\Seller;
use App\Service\Order\OrderService;
use Doctrine\ORM\NonUniqueResultException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_SELLER')]
#[Route('/ma-boutique/mes-ventes', name: 'app_seller_order')]
class OrderController extends AbstractController
{
    /**
     * @var OrderService
     */
    private OrderService $orderService;

    /**
     * @param OrderService $orderService
     */
    public function __construct(OrderService $orderService)
    {
        $this->orderService = $orderService;
    }

    /**
     * @param Request $request
     * @return Response
     */
    #[Route('/', name: '_index', methods: ['GET'])]
    public function index(Request $request): Response
    {
        $parameters = $request->query->all();
        $sort = $parameters['sort'] ?? null;
        $page = $request->query->get('page');
        $limit = $request->query->get('limit');

        $orders = $this->orderService->getOrdersBySeller($this->getUser(), $sort, $page, $limit);

        return $this->render('seller/order/index.html.twig', [
            'orders' => $orders['data'],
            'pagination' => $orders['pagination'],
        ]);
    }

    /**
     * @param Order $order
     * @return Response
     */
    #[Route('/{slug}', name: '_show', methods: ['GET'])]
    public function show(Order $order): Response
    {
        /** @var Seller $seller */
        $seller = $this->getUser();

        try {
            $order = $this->orderService->getOrderForSeller($order, $seller);
        } catch (NonUniqueResultException $e) {
            $this->addFlash('danger', 'La commande n\'existe pas');

            return $this->redirectToRoute('app_seller_order_index');
        }


        return $this->render('seller/order/show.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @param Request $request
     * @param OrderItemSeller $orderItemSeller
     * @return Response
     */
    #[Route('/expedier/{id}', name: '_ship')]
    public function ship(Request $request, OrderItemSeller $orderItemSeller): Response
    {
        $token = $request->query->get('_csrf_token');

        $order = $orderItemSeller->getOrder();

        if (!$this->isCsrfTokenValid('order-ship-' . $order->getId(), $token)) {
            $this->addFlash('danger', 'Le token est invalide');

            return $this->redirectToRoute('app_seller_order_index');
        }

        /** @var Seller $seller */
        $seller = $this->getUser();

        $this->orderService->ship($order, $seller);

        $this->addFlash('success', 'La commande a été marqué comme expédiée');

        return $this->redirectToRoute('app_seller_order_index');
    }

    /**
     * @param Request $request
     * @param Order $order
     * @return JsonResponse
     */
    #[Route('/supprimer/{slug}', name: '_delete', methods: ['DELETE'])]
    public function delete(Request $request, Order $order): JsonResponse
    {
        $token = $request->headers->get('X-CSRF-Token');

        if (!$this->isCsrfTokenValid('order-delete-' . $order->getId(), $token)) {
            return $this->json([
                'status' => 'error',
                'message' => 'Le token est invalide',
            ], Response::HTTP_FORBIDDEN);
        }

        /** @var Seller $seller */
        $seller = $this->getUser();

        $this->orderService->deleteOrderForSeller($order, $seller);

        return $this->json([
            'status' => 'success',
            'message' => 'La commande a été supprimée',
        ], Response::HTTP_OK);
    }
}

templates/seller/order/_datalist.html.twig
{% import 'macros/datalist_macros.html.twig' as datalist %}
{% import 'macros/table_macros.html.twig' as table %}

{{ datalist.datalistStart() }}

{{ datalist.datalistRow(datalist.datalistItem('Date de la commande', order.orderDate|date('d/m/Y H:i'))) }}

{{ datalist.datalistRow(datalist.datalistItem(
    'Status',
    order.orderItemSellers.first.status == 'cart' ? 'panier' : order.orderItemSellers.first.status == 'pending' ? 'à traiter' : 'expédié',
    'order-status badge badge-' ~ (order.orderItemSellers.first.status == 'pending' ? 'blue' : 'green') ~ ' badge-lowercase'
)) }}

{{ datalist.datalistRow(datalist.datalistItem(
    'Paiement',
    order.payment.status == 'pending' ? 'en attente' : order.payment.status == 'failed' ? 'échoué' : 'payé',
    'badge badge-' ~ (order.payment.status == 'failed' ? 'red ' : order.payment.status == 'pending' ? 'blue ' : 'green ') ~ 'badge-lowercase')
) }}

{{ datalist.datalistRowStart() }}

{{ datalist.datalistItemStart('Commande') }}

{{ datalist.dataListArray(
    table.tableStart('datalist-table') ~
    table.tableHeader([
        table.tableHeaderItem('Produit'),
        table.tableHeaderItem('Quantité'),
        table.tableHeaderItem('Prix unitaire'),
        table.tableHeaderItem('Promotion'),
        table.tableHeaderItem('Prix remisé'),
        table.tableHeaderItem('Prix total')
    ]) ~
    table.tableBodyStart()
) }}

{% for orderItem in order.orderItems %}
    {{ table.tableRowStart() }}
    {{ table.tableRowItem(orderItem.product.name, 'Produit') }}
    {{ table.tableRowItem(orderItem.quantity ~ ' pièce(s)', 'Quantité') }}
    {{ table.tableRowItem(orderItem.product.price|number_format(2, ',') ~ ' €', 'Prix unitaire') }}
    {{ table.tableRowItem(orderItem.product.discount ~ ' %', 'Promotion') }}
    {{ table.tableRowItem(orderItem.product.priceWithDiscount|number_format(2, ',') ~ ' €', 'Prix remisé') }}
    {{ table.tableRowItem(orderItem.total|number_format(2, ',') ~ ' €', 'Prix total') }}
    {{ table.tableRowEnd() }}
{% endfor %}

{{ datalist.dataListArray(
    table.tableBodyEnd() ~
    table.tableEnd()
) }}

{{ datalist.datalistItemEnd() }}

{{ datalist.datalistRowEnd() }}

{{ datalist.datalistRow(
    datalist.datalistItemRaw(
        'Informations de livraison',
        datalist.dataListArray(
            table.tableStart('datalist-table') ~
            table.tableHeader([
                table.tableHeaderItem('Nom'),
                table.tableHeaderItem('Prénom'),
                table.tableHeaderItem('Adresse'),
                table.tableHeaderItem('Ville'),
                table.tableHeaderItem('Code postal'),
                table.tableHeaderItem('Numéro de téléphone'),
                table.tableHeaderItem('Email')
            ]) ~
            table.tableBodyStart() ~
            table.tableRowItem(order.customer.lastname, 'Nom') ~
            table.tableRowItem(order.customer.firstname, 'Prénom') ~
            table.tableRowItem(order.customer.getAddress, 'Adresse') ~
            table.tableRowItem(order.customer.city, 'Ville') ~
            table.tableRowItem(order.customer.postalCode, 'Code postal') ~
            table.tableRowItem(order.customer.phone, 'Numéro de téléphone') ~
            table.tableRowItem(order.customer.email, 'Email') ~
            table.tableBodyEnd() ~
            table.tableEnd()
        )
    )
) }}

{{ datalist.datalistEnd() }}

templates/seller/order/_table.html.twig
{% import 'macros/table_macros.html.twig' as macros %}

{% set parameters = app.request.query.all %}
{% set sortArray = parameters['sort'] ?? {} %}
{% set sort = sortArray|first ? sortArray|keys|first : '' %}
{% set order = sortArray|first ? sortArray|first : 'ASC' %}

{{ macros.tableStart() }}

{{ macros.tableHeader([
    macros.tableHeaderItem(macros.tableHeaderSpan('Client')),
    macros.tableHeaderItem(
        macros.tableHeaderLink(
            'Date de la commande',
            order == 'ASC' and sort == 'orderDate' ? 'fa-arrow-up' : order == 'DESC' and sort == 'orderDate' ? 'fa-arrow-down' : 'fa-sort',
            path('app_seller_order_index', {'sort[orderDate]': order == 'ASC' and sort == 'orderDate' ? 'DESC' : 'ASC', })),
    ),
    macros.tableHeaderItem(
      macros.tableHeaderSpan('Montant de la commande')
    ),
    macros.tableHeaderItem(
        macros.tableHeaderLink(
            'Statut',
            order == 'ASC' and sort == 'status' ? 'fa-arrow-up' : order == 'DESC' and sort == 'status' ? 'fa-arrow-down' : 'fa-sort',
            path('app_seller_order_index', {'sort[status]': order == 'ASC' and sort == 'status' ? 'DESC' : 'ASC', })),
    ),
    macros.tableHeaderItem(macros.tableHeaderSpan('Paiement')),
    macros.tableHeaderItem(macros.tableHeaderSpan('Actions', 'sr-only')),
]) }}

{{ macros.tableBodyStart() }}

{% for order in orders %}
    {{ macros.tableRow([
        macros.tableRowItem(order.customer.userIdentifier, 'Client'),
        macros.tableRowItem(order.orderDate|date('d/m/Y H:i'), 'Date de la commande'),
        macros.tableRowItem(order.getTotalForSeller(app.user), 'Montant de la commande', '€'),
        macros.tableRowItem(order.getOrderItemSeller(app.user.id).status == 'cart' ? 'panier' : order.getOrderItemSeller(app.user.id).status == 'pending' ? 'à traiter' : 'expédié', 'Statut', '', 'order-status badge badge-' ~ (order.getOrderItemSeller(app.user.id).status == 'pending' ? 'blue' : 'green') ~ ' badge-lowercase'),
        macros.tableRowItem(order.payment.status == 'pending' ? 'en attente' : order.payment.status == 'failed' ? 'échoué' : 'payé', 'Paiement', '', 'badge badge-' ~ (order.payment.status == 'failed' ? 'red ' : order.payment.status == 'pending' ? 'blue ' : 'green ') ~ 'badge-lowercase'),
        macros.tableActionDropdown([
            macros.tableActionDropdownItem(
                path('app_seller_order_show', {slug: order.slug}),
                'Aperçu',
                'action-show',
                'fa-eye',
            ),
            order.getOrderItemSeller(app.user.id).status != "on_delivery" ? macros.tableActionDropDownItem(
                path('app_seller_order_ship', {id: order.getOrderItemSeller(app.user.id).id, '_csrf_token': csrf_token('order-ship-' ~ order.id)}),
                'Expédié',
                'action-edit',
                'fa-envelope',
            ) : null,
            macros.tableActionDropdownItem(
                path('app_seller_order_delete', {slug: order.slug}),
                'Supprimer',
                'action-delete',
                'fa-trash',
                csrf_token('order-delete-' ~ order.id)
            ),
        ])
    ]) }}
{% endfor %}

{{ macros.tableBodyEnd() }}

{{ macros.tableEnd() }}

templates/seller/order/index.html.twig
{% extends 'user/base_user.html.twig' %}

{% block section %}

    <section class="content-section">
        <div class="content-header">
            <h2>Liste des ventes</h2>
        </div>
        <section class="content-table">
            {{ include('seller/order/_table.html.twig') }}
            {{ include('components/_pagination.html.twig') }}
        </section>
    </section>
{% endblock %}

templates/seller/order/show.html.twig
{% extends 'user/base_user.html.twig' %}

{% block section %}

    <section class="content-section">
        <div class="content-header">
            <h2>Commande n° {{ order.id }}</h2>
            <a href="{{ path('app_seller_order_index') }}" class="button button-blue">Retour</a>
        </div>
        <section>
            {{ include('seller/order/_datalist.html.twig') }}
        </section>
    </section>
{% endblock %}