src/Entity/EntityInterface.php
<?php

namespace App\Entity;

use DateTimeInterface;

interface EntityInterface
{
    /**
     * @return int|null
     */
    public function getId(): ?int;

    /**
     * @return DateTimeInterface|null
     */
    public function getCreatedAt(): ?DateTimeInterface;

    /**
     * @return DateTimeInterface|null
     */
    public function getUpdatedAt(): ?DateTimeInterface;
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Annotation\SlugProperty;
use App\Repository\ProductRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @SlugProperty(property="name")
 */
#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product extends AbstractEntity
{
    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\NotBlank(message: 'Veuillez saisir le nom du produit')]
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Le nom du produit doit contenir au moins {{ limit }} caractères',
        maxMessage: 'Le nom du produit doit contenir au maximum {{ limit }} caractères',
    )]
    #[Groups(['product:list'])]
    private string $name = '';

    /**
     * @var string
     */
    #[ORM\Column(type: 'text')]
    #[Assert\NotBlank(message: 'Veuillez saisir la description du produit')]
    private string $description = '';

    /**
     * @var float
     */
    #[ORM\Column(type: 'float')]
    #[Assert\NotBlank(message: 'Veuillez saisir le prix du produit')]
    #[Assert\Positive(message: 'Le prix du produit doit être positif')]
    #[Groups(['product:list'])]
    private float $price = 0.0;

    /**
     * @var int
     */
    #[ORM\Column(type: 'integer')]
    #[Assert\NotBlank(message: 'Veuillez saisir la quantité du produit')]
    #[Assert\Positive(message: 'La quantité du produit doit être positive')]
    #[Groups(['product:list'])]
    private int $quantity = 0;


    /**
     * @var Seller|null
     */
    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Seller $seller = null;

    /**
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OrderItem::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection|ArrayCollection $orderItems;
    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Picture::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection|ArrayCollection $pictures;

    /**
     * @var int|null
     */
    #[ORM\Column(nullable: true)]
    #[Assert\Positive(message: 'Le pourcentage de réduction doit être positif')]
    #[Groups(['product:list'])]
    private ?int $discount = null;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\ManyToMany(targetEntity: Caracteristic::class, inversedBy: 'products')]
    private Collection|ArrayCollection $caracteristics;

    /**
     * @var float|null
     */
    #[ORM\Column(nullable: true)]
    private ?float $shippingFee = null;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\ManyToMany(targetEntity: Category::class, mappedBy: 'products',cascade: ['persist'])]
    private Collection|ArrayCollection $categories;

    /**
     * @var Brand|null
     */
    #[ORM\ManyToOne(targetEntity: Brand::class, cascade: ['persist'], inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Brand $brand = null;


    public function __construct()
    {
        parent::__construct();
        $this->updatedAt = new DateTime();
        $this->categories = new ArrayCollection();
        $this->orderItems = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->caracteristics = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Product
     */
    public function setName(string $name): Product
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Product
     */
    public function setDescription(string $description): Product
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return float
     */
    public function getPrice(): float
    {
        return $this->price;
    }

    /**
     * @param float $price
     * @return Product
     */
    public function setPrice(float $price): Product
    {
        $this->price = round($price, 2);
        return $this;
    }

    /**
     * @return int
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * @param int $quantity
     * @return Product
     */
    public function setQuantity(int $quantity): Product
    {
        $this->quantity = $quantity;
        return $this;
    }

    /**
     * @param int $quantity
     * @return Product
     */
    public function addQuantity(int $quantity): Product
    {
        $this->quantity += $quantity;
        return $this;
    }

    /**
     * @return Seller|null
     */
    public function getSeller(): ?Seller
    {
        return $this->seller;
    }

    /**
     * @param Seller|null $seller
     * @return $this
     */
    public function setSeller(?Seller $seller): self
    {
        $this->seller = $seller;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param string $slug
     * @return $this
     */
    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    /**
     * @param OrderItem $orderItem
     * @return $this
     */
    public function addOrderItem(OrderItem $orderItem): self
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setProduct($this);
        }

        return $this;
    }

    /**
     * @param OrderItem $orderItem
     * @return $this
     */
    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getProduct() === $this) {
                $orderItem->setProduct(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    /**
     * @param Picture $picture
     * @return $this
     */
    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setProduct($this);
        }

        return $this;
    }

    /**
     * @param Collection $pictures
     * @return $this
     */
    public function setPictures(Collection $pictures): self
    {
        foreach ($pictures as $picture) {
            $this->addPicture($picture);
        }
        return $this;
    }

    /**
     * @param Picture $picture
     * @return $this
     */
    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProduct() === $this) {
                $picture->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return int|null
     */
    public function getDiscount(): ?int
    {
        return $this->discount;
    }

    /**
     * @param int|null $discount
     * @return $this
     */
    public function setDiscount(?int $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    /**
     * @return Collection<int, Caracteristic>
     */
    public function getCaracteristics(): Collection
    {
        return $this->caracteristics;
    }

    /**
     * @param Caracteristic $caracteristic
     * @return $this
     */
    public function addCaracteristic(Caracteristic $caracteristic): self
    {
        if (!$this->caracteristics->contains($caracteristic)) {
            $this->caracteristics->add($caracteristic);
        }

        return $this;
    }

    /**
     * @param Caracteristic $caracteristic
     * @return $this
     */
    public function removeCaracteristic(Caracteristic $caracteristic): self
    {
        $this->caracteristics->removeElement($caracteristic);

        return $this;
    }

    /**
     * @return float
     */
    public function getPriceWithDiscount(): float
    {
        if ($this->discount === null) {
            return $this->price;
        }
        $newPrice = $this->price - ($this->price * $this->discount / 100);
        return round($newPrice, 2);
    }

    /**
     * @return float|null
     */
    public function getShippingFee(): ?float
    {
        return $this->shippingFee;
    }

    /**
     * @param float $shippingFee
     * @return $this
     */
    public function setShippingFee(float $shippingFee): self
    {
        $this->shippingFee = $shippingFee;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    /**
     * @param Category $category
     * @return $this
     */
    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->addProduct($this);
        }

        return $this;
    }

    /**
     * @param Category $category
     * @return $this

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Product;
use App\Form\FilterForm\FilterFormType;
use App\Service\Category\CategoryService;
use App\Service\Form\FormProcessor;
use App\Service\Product\ProductService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/produits', name: 'app_product')]
class ProductController extends AbstractController
{
    /**
     * @var ProductService
     */
    private ProductService $productService;
    /**
     * @var CategoryService
     */
    private CategoryService $categoryService;
    /**
     * @var FormProcessor
     */
    private FormProcessor $formProcessor;

    /**
     * @param ProductService $productService
     * @param CategoryService $categoryService
     * @param FormProcessor $formProcessor
     */
    public function __construct(ProductService $productService, CategoryService $categoryService, FormProcessor $formProcessor)
    {
        $this->productService = $productService;
        $this->categoryService = $categoryService;
        $this->formProcessor = $formProcessor;
    }

    /**
     * @param Request $request
     * @param Category $category
     * @param string|null $subCategorySlug
     * @return Response
     */
    #[Route('/{categorySlug}/{subCategorySlug?}', name: '_index', requirements: [
        'categorySlug' => '[a-zA-Z0-9-_]+',
        'subCategorySlug' => '[a-zA-Z0-9-_]+'
    ])]
    #[ParamConverter('category', options: ['mapping' => ['categorySlug' => 'slug']])]
    public function index(
        Request $request,
        Category $category,
        ?string $subCategorySlug = null
    ): Response {
        $order = $request->query->get('order');
        $page = $request->query->get('page');
        $limit = $request->query->get('limit');

        $subCategory = null;
        if ($subCategorySlug !== null) {
            // Récupérer la sous-catégorie en fonction du slug et de la catégorie parente
            $subCategory = $this->categoryService->getSubCategoryBySlug($subCategorySlug, $category);
        }

        $products = $this->productService->getProductsByCategory($category, $subCategory, $order, $page, $limit);

        $minPrice = $this->productService->getMinPrice();
        $maxPrice = $this->productService->getMaxPrice();

        $filterForm = $this->formProcessor->create(FilterFormType::class, null, [
            'minPrice' => $minPrice,
            'maxPrice' => $maxPrice,
            'category' => $subCategory !== null ? $subCategory : $category,
        ]);

        $this->formProcessor->handleRequest($request, $filterForm);

        if ($this->formProcessor->isValid($filterForm)) {
            $products = $this->productService->getProductsByFilter($filterForm->getData(), $category, $subCategory, $order, $page, $limit);
        }

        return $this->render('product/index.html.twig', [
            'products' => $products,
            'category' => $category,
            'subCategory' => $subCategory,
            'filterForm' => $filterForm->createView(),
        ]);
    }

    /**
     * @param Category $category
     * @param Category $subCategory
     * @param Product $product
     * @return Response
     */
    #[Route('/{categorySlug}/{subCategorySlug}/{productSlug}', name: '_show', requirements: [
        'categorySlug' => '[a-zA-Z0-9-_]+',
        'subCategorySlug' => '[a-zA-Z0-9-_]+',
        'productSlug' => '[a-zA-Z0-9-_]+',
    ])]
    #[ParamConverter('category', options: ['mapping' => ['categorySlug' => 'slug']])]
    #[ParamConverter('subCategory', options: ['mapping' => ['subCategorySlug' => 'slug']])]
    #[ParamConverter('product', options: ['mapping' => ['productSlug' => 'slug']])]
    public function show(
        Category $category,
        Category $subCategory,
        Product   $product
    ): Response
    {
        return $this->render('product/show.html.twig', [
            'category' => $category,
            'subCategory' => $subCategory,
            'product' => $product,
        ]);
    }
}

src/Controller/Seller/MainController.php
<?php

namespace App\Controller\Seller;

use App\Service\Order\OrderService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_SELLER')]
#[Route('/ma-boutique', name: 'app_seller')]
class MainController extends AbstractController
{
    /**
     * @var OrderService
     */
    private OrderService $orderService;

    /**
     * @param OrderService $orderService
     */
    public function __construct(OrderService $orderService)
    {
        $this->orderService = $orderService;
    }

    /**
     * @return Response
     */
    #[Route('/', name: '_index')]
    public function index(): Response
    {
        $orders = $this->orderService->getOrdersForSeller($this->getUser());
        $incomesChart = $this->orderService->getTotalIncomesPerMonthChart($this->getUser(), $orders);

        $ordersChart = $this->orderService->getTotalOrdersPerMonthChart($orders);

        $productPerParentCategoryChart = $this->orderService->getTotalProductSoldPerCategoriesChart($this->getUser(), $orders, true);

        $productPerCategoryChart = $this->orderService->getTotalProductSoldPerCategoriesChart($this->getUser(), $orders, false);

        $topProductsChart = $this->orderService->getTotalTopProductsSoldChart($this->getUser(), $orders);

        $cartAverageChart = $this->orderService->getCartAveragePerMonthChart($this->getUser(), $orders);


        return $this->render('seller/main/index.html.twig', [
            'incomesChart' => $incomesChart,
            'ordersChart' => $ordersChart,
            'productPerParentCategoryChart' => $productPerParentCategoryChart,
            'productPerCategoryChart' => $productPerCategoryChart,
            'topProductsChart' => $topProductsChart,
            'cartAverageChart' => $cartAverageChart,
        ]);
    }
}

templates/seller/product/_datalist.html.twig
{% import 'macros/datalist_macros.html.twig' as macros %}

{{ macros.datalistStart() }}
{{ macros.datalistRow(macros.datalistItem('Nom', product.name)) }}
{{ macros.datalistRow(macros.datalistItemRaw('Description', product.description)) }}
{{ macros.datalistRow(macros.datalistItem('Price', product.price ~ " €" )) }}
{{ macros.datalistRow(macros.datalistItem('Promotion', product.discount ~ " %" )) }}
{{ macros.datalistRow(macros.datalistItem('Prix promotionnel', product.priceWithDiscount ~ " €")) }}
{{ macros.datalistRow(macros.datalistItem('Quantité', product.quantity ~ ' pièce')) }}
{{ macros.datalistRow(macros.datalistItem('Catégorie', product.categories[0].name, 'badge badge-green badge-lowercase')) }}
{{ macros.datalistRow(macros.datalistItem('Sous-catégorie', product.categories[1].name, 'badge badge-green badge-lowercase')) }}
{{ macros.datalistRow(macros.datalistItem('Marque', product.brand.name)) }}
{{ macros.datalistRowStart('data-pictures') }}
{% for picture in product.pictures %}
{{ macros.datalistPicture('Image n°' ~ loop.index, picture.thumbnail) }}
{% endfor %}
{{ macros.datalistRowEnd() }}

{{ macros.datalistRow(macros.datalistItem('Date de création', product.createdAt|date('d/m/Y H:i'))) }}
{{ macros.datalistRow(macros.datalistItem('Date de modification', product.updatedAt|date('d/m/Y H:i'))) }}

{{ macros.datalistEnd() }}

templates/seller/product/_form.html.twig
{% import 'macros/crud_form_macros.html.twig' as macros %}

{{ form_start(form, {'attr': {'class': 'crud-form'}}) }}
        {{ macros.formField(form.categories.vars.label, form.categories, 'form-field', 'tom-select') }}
        {{ macros.formField(form.name.vars.label, form.name,'form-field', 'form-input-text') }}
        {{ macros.formField(form.description.vars.label, form.description, 'form-field') }}

        {{ macros.formGroup(
            macros.formFieldSymbol(form.price.vars.label, form.price, 'form-field', 'form-input-price') ~
            macros.formFieldSymbol(form.discount.vars.label, form.discount, 'form-field', 'form-input-percentage')
        ) }}

        {{ macros.formGroup(
            macros.formField(form.quantity.vars.label, form.quantity, 'form-field') ~
            macros.formField(form.brand.vars.label, form.brand, 'form-field', 'tom-select select-unique')
        ) }}

        {{ macros.formField(form.caracteristics.vars.label, form.caracteristics,'form-field', 'tom-select') }}

        {{ macros.crudCollectionStart(form.pictures) }}

        {% for field in form.pictures %}
            {{ macros.formGroup(
                macros.formFieldCollection(
                    macros.formField(field.thumbnail.vars.label, field.thumbnail) ~
                    macros.formField(field.file.vars.label, field.file, 'form-field-collection', 'form-input-file') ~
                    macros.formField(field.alt.vars.label, field.alt, 'form-field-collection', 'form-input-text'),
                    'crud-collection-field'
                ) ~
                macros.formFieldCollectionDelete("crud-collection-item-remove"),
            ) }}
            {{ macros.formGroup(
                macros.formThumbnail(field.thumbnail.vars.label,field.thumbnail.vars.value, field.alt.vars.value),
                'crud-collection-thumbnail'
            ) }}
        {% endfor %}

        {{ macros.crudCollectionEnd() }}

        {{ macros.formGroup('<button type="button" id="add-another-item" class="button button-blue">Ajouter une image</button>') }}
        {{ macros.formGroup('<button type="submit" class="button button-blue">Publier</button>') }}
{{ form_end(form) }}

templates/seller/product/_table.html.twig
{% import 'macros/table_macros.html.twig' as macros %}

{% set parameters = app.request.query.all %}
{% set sortArray = parameters['sort'] ?? {} %}
{% set sort = sortArray|first ? sortArray|keys|first : '' %}
{% set order = sortArray|first ? sortArray|first : 'ASC' %}

{{ macros.tableStart() }}

{{ macros.tableHeader([
    macros.tableHeaderItem(
        macros.tableHeaderLink(
            'Nom',
            order == 'ASC' and sort == 'name' ? 'fa-arrow-up' : order == 'DESC' and sort == 'name' ? 'fa-arrow-down' : 'fa-sort',
            path('app_seller_product_index', {'sort[name]': order == 'ASC' and sort == 'name' ? 'DESC' : 'ASC', }),
        ),
    ),
    macros.tableHeaderItem(
        macros.tableHeaderLink(
            'Prix',
            order == 'ASC' and sort == 'price' ? 'fa-arrow-up' : order == 'DESC' and sort == 'price' ? 'fa-arrow-down' : 'fa-sort',
            path('app_seller_product_index', {'sort[price]': order == 'ASC' and sort == 'price' ? 'DESC' : 'ASC', })),
    ),
    macros.tableHeaderItem(
        macros.tableHeaderLink(
            'Promotion',
            order == 'ASC' and sort == 'discount' ? 'fa-arrow-up' : order == 'DESC' and sort == 'discount' ? 'fa-arrow-down' : 'fa-sort',
            path('app_seller_product_index', {'sort[discount]': order == 'ASC' and sort == 'discount' ? 'DESC' : 'ASC', })),
    ),
    macros.tableHeaderItem(
        macros.tableHeaderLink(
            'Quantité',
            order == 'ASC' and sort == 'quantity' ? 'fa-arrow-up' : order == 'DESC' and sort == 'quantity' ? 'fa-arrow-down' : 'fa-sort',
            path('app_seller_product_index', {'sort[quantity]': order == 'ASC' and sort == 'quantity' ? 'DESC' : 'ASC', })),
    ),
    macros.tableHeaderItem(macros.tableHeaderSpan('Catégories')),
    macros.tableHeaderItem(
        macros.tableHeaderLink(
            'Dernière modification',
            order == 'ASC' and sort == 'updatedAt' ? 'fa-arrow-up' : order == 'DESC' and sort == 'updatedAt' ? 'fa-arrow-down' : 'fa-sort',
            path('app_seller_product_index', {'sort[updatedAt]': order == 'ASC' and sort == 'updatedAt' ? 'DESC' : 'ASC', })),
    ),
    macros.tableHeaderItem(macros.tableHeaderSpan('Actions', 'sr-only')),
]) }}

{{ macros.tableBodyStart() }}

{% for product in products %}
    {% set parentCategories = product.categories|filter(c => c.parent is not null) %}
    {% if parentCategories is not empty %}
        {% set categoriesRow = macros.tableRowCollection(parentCategories,'Catégories', 'name', ) %}
    {% else %}
        {% set categoriesRow = macros.tableRowItem('Aucune', 'Catégories') %}
    {% endif %}

    {{ macros.tableRow([
        macros.tableRowItem(product.name, 'Nom'),
        macros.tableRowItem(product.price, 'Prix', "€"),
        macros.tableRowItem(product.discount is null ? 'Aucune' : product.discount, 'Promotion', "%" ),
        macros.tableRowItem(product.quantity, 'Quantité', "pièces"),
        categoriesRow,
        macros.tableRowItem(product.updatedAt|date('d/m/Y H:i'), 'Dernière modification'),
        macros.tableActionDropdown([
            macros.tableActionDropdownItem(
                path('app_seller_product_show', {slug: product.slug}),
                'Consulter',
                'action-show',
                'fa-eye'
            ),
            macros.tableActionDropdownItem(
                path('app_seller_product_edit', {slug: product.slug}),
                'Modifier',
                'action-update',
                'fa-edit'
            ),
            macros.tableActionDropdownItem(
                path('app_seller_product_delete', {slug: product.slug}),
                'Supprimer',
                'action-delete',
                'fa-trash',
                csrf_token('product-delete-' ~ product.id)
            ),
        ])
    ]) }}
{% endfor %}

{{ macros.tableBodyEnd() }}

{{ macros.tableEnd() }}

templates/seller/product/add.html.twig
{% extends 'user/base_user.html.twig' %}

{% block section %}
    <section class="content-section">
        <div class="content-header">
            <h2>Ajouter un produit dans ma boutique</h2>
            <a href="{{ path('app_seller_product_index') }}" class="button button-blue">Retour</a>
        </div>
        <section>
            {{ include('seller/product/_form.html.twig') }}
        </section>
    </section>
{% endblock %}

templates/seller/product/edit.html.twig
{% extends 'user/base_user.html.twig' %}

{% block section %}
    <section class="content-section">
        <div class="content-header">
            <h2>Modifier un produit</h2>
            <a href="{{ path('app_seller_product_index') }}" class="button button-blue">Retour</a>
        </div>
        <section>
            {{ include('seller/product/_form.html.twig') }}
        </section>
    </section>
{% endblock %}

templates/seller/product/index.html.twig
{% extends 'user/base_user.html.twig' %}

{% block section %}

    <section class="content-section">
        <div class="content-header">
            <h2>Liste des produits</h2>
            <a href="{{ path('app_seller_product_add') }}" class="button button-blue">Ajouter un produit</a>
        </div>
        <section class="content-table">
            {{ include('seller/product/_table.html.twig') }}
            {{ include('components/_pagination.html.twig') }}
        </section>
    </section>
{% endblock %}

templates/seller/product/show.html.twig
{% extends 'user/base_user.html.twig' %}

{% block section %}
    <section class="content-section">
        <div class="content-header">
            <h2>Consulter un produit</h2>
            <a href="{{ path('app_seller_product_index') }}" class="button button-blue">Retour</a>
        </div>
        <section>
            {{ include('seller/product/_datalist.html.twig') }}
        </section>
    </section>
{% endblock %}