src/Entity/EntityInterface.php
<?php

namespace App\Entity;

use DateTimeInterface;

interface EntityInterface
{
    /**
     * @return int|null
     */
    public function getId(): ?int;

    /**
     * @return DateTimeInterface|null
     */
    public function getCreatedAt(): ?DateTimeInterface;

    /**
     * @return DateTimeInterface|null
     */
    public function getUpdatedAt(): ?DateTimeInterface;
}

src/Entity/OrderInterface.php
<?php

namespace App\Entity;

use DateTimeInterface;

interface OrderInterface
{
    public function getOrderDate(): ?DateTimeInterface;
    public function getDeliveryDate(): ?DateTimeInterface;
    public function getOrderStatus(): string;
    public function getTotalAmount(): float;
    public function getCustomer(): ?CustomerInterface;
    public function getOrderItems(): array;
    /**
     * @todo Implémenter une méthode getPayment() qui retourne un objet de type PaymentInterface
     */
//    public function getPayment();
}

src/Entity/Payment.php
<?php

namespace App\Entity;

use App\Annotation\SlugProperty;
use App\Entity\Interface\PaymentInterface;
use App\Repository\PaymentRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @SlugProperty(property="id")
 */
#[ORM\Entity(repositoryClass: PaymentRepository::class)]
#[UniqueEntity('paymentToken', message: 'Le token de paiement doit être unique')]
class Payment extends AbstractEntity implements PaymentInterface
{
    /**
     * @var float
     */
    #[ORM\Column(type: 'float')]
    private float $amount = 0.0;

    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 3)]
    private string $currency = self::CURRENCY_EUR;

    /**
     * @var string
     */
    #[ORM\Column(type: 'text')]
    private string $description = '';

    /**
     * @var string|null
     */
    #[ORM\Column(type: 'string', length: 255)]
    private ?string $status = '';

    /**
     * @var Order|null
     */
    #[ORM\OneToOne(mappedBy: 'payment', cascade: ['persist', 'remove'])]
    private ?Order $order = null;

    const STATUS_PENDING = 'pending';
    const STATUS_PAID = 'paid';
    const STATUS_FAILED = 'failed';
    const CURRENCY_EUR = 'EUR';

    const CREDIT_CARD = 'credit_card';
    const PAYPAL = 'paypal';

    public function __construct()
    {
        parent::__construct();
        $this->createdAt = new DateTime();
    }
    /**
     * @return float
     */
    public function getAmount(): float
    {
        return $this->amount;
    }

    /**
     * @param float $amount
     * @return Payment
     */
    public function setAmount(float $amount): Payment
    {
        $this->amount = $amount;
        return $this;
    }

    /**
     * @return string
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    /**
     * @param string $currency
     * @return Payment
     */
    public function setCurrency(string $currency): Payment
    {
        $this->currency = $currency;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Payment
     */
    public function setDescription(string $description): Payment
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param string|null $status
     * @return Payment
     */
    public function setStatus(?string $status): Payment
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return Order|null
     */
    public function getOrder(): ?Order
    {
        return $this->order;
    }

    /**
     * @param Order|null $order
     * @return $this
     */
    public function setOrder(?Order $order): self
    {
        // unset the owning side of the relation if necessary
        if ($order === null && $this->order !== null) {
            $this->order->setPayment(null);
        }

        // set the owning side of the relation if necessary
        if ($order !== null && $order->getPayment() !== $this) {
            $order->setPayment($this);
        }

        $this->order = $order;

        return $this;
    }
}

src/Entity/UserInterface.php
<?php

namespace App\Entity;

interface UserInterface
{
    /**
     * @return string|null
     */
    public function getFirstName(): ?string;

    /**
     * @return string|null
     */
    public function getLastName(): ?string;

    /**
     * @return string|null
     */
    public function getEmail(): ?string;

    /**
     * @return string|null
     */
    public function getAddress(): ?string;

    /**
     * @return string|null
     */
    public function getPhone(): ?string;
}

src/Controller/PaymentController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\OrderItemSeller;
use App\Entity\Payment;
use App\Manager\CartManager;
use App\Manager\PaymentManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;


#[IsGranted('ROLE_CUSTOMER')]
#[Route('/paiement', name: 'app_payment')]
class PaymentController extends AbstractController
{
    /**
     * @var CartManager
     */
    private CartManager $cartManager;
    /**
     * @var PaymentManager
     */
    private PaymentManager $paymentManager;

    /**
     * @param CartManager $cartManager
     * @param PaymentManager $paymentManager
     */
    public function __construct(
        CartManager    $cartManager,
        PaymentManager $paymentManager,
    )
    {
        $this->cartManager = $cartManager;
        $this->paymentManager = $paymentManager;
    }

    /**
     * @return Response
     */
    #[Route('/', name: '_index')]
    public function index(): Response
    {
        $cart = $this->cartManager->getCurrentCart();

        $cart->setStatus(Order::STATUS_PENDING);


        $this->cartManager->saveCart($cart);

        $payment = $this->paymentManager->getPayment($cart);

        $this->paymentManager->savePayment($payment);

        $paymentSession = $this->paymentManager->getPaymentSession($payment);

        return new RedirectResponse($paymentSession->url, 302, ['Content-Type' => 'application/json']);
    }

    /**
     * @param Order $order
     * @return Response
     */
    #[Route('/succes/{id}', name: '_success')]
    public function paymentSuccess(Order $order): Response
    {
        if ($order->getStatus() === Order::STATUS_PENDING) {
            $order->setStatus(Order::STATUS_COMPLETED);

            foreach ($order->getOrderItemSellers() as $orderItemSeller) {
                $orderItemSeller->setStatus(OrderItemSeller::STATUS_PENDING);
            }

            $this->cartManager->saveCart($order);
        }

        $payment = $this->paymentManager->getPayment($order);

        if ($order->getStatus() === Order::STATUS_COMPLETED && $payment->getStatus() === Payment::STATUS_PENDING) {
            $payment->setStatus(Payment::STATUS_PAID);
            $this->paymentManager->savePayment($payment);
        }

        $this->addFlash('success', 'Votre commande a bien été validée, vous allez recevoir un mail de confirmation !');

        return $this->render('payment/index.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @param Order $order
     * @return Response
     */
    #[Route('/echec/{id}', name: '_failed')]
    public function paymentFailed(Order $order): Response
    {
        $payment = $this->paymentManager->getPayment($order);

        if ($payment->getStatus() === Payment::STATUS_PENDING) {
            $payment->setStatus(Payment::STATUS_FAILED);

            foreach ($order->getOrderItemSellers() as $orderItemSeller) {
                $orderItemSeller->setStatus(OrderItemSeller::STATUS_CART);
            }
            $this->paymentManager->savePayment($payment);
        }

        $this->addFlash('danger', 'Votre commande a échouée, nous vous invitons à réessayer !');
        return $this->render('payment/index.html.twig', [
            'order' => $order,
        ]);
    }
}

templates/payment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiment{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('paymentPage') }}
{% endblock %}

{% block body %}
    <div class="order-page-section">
        <section class="order-section">
            <h1>Commande n°{{ order.id }}</h1>
            <ul class="order-list">
                <li class="order-overview-item-headers">
                    <p class="order-overview-item-product">Produit</p>
                    <p class="order-overview-item-value">Prix</p>
                    <p class="order-overview-item-quantity">Quantité</p>
                    <p class="order-overview-item-total">Total</p>
                </li>
                {% for orderItem in order.orderItems %}
                    <li class="order-overview-item">
                        <p class="order-overview-item-product">
                            <img src="{{ orderItem.product.pictures[0].path }}"
                                 alt="{{ orderItem.product.pictures[0].alt }}"
                                 class="order-overview-item-product-image">
                            <span class="order-overview-item-product-name">{{ orderItem.product.name }}</span>
                        </p>
                        <p class="order-overview-item-value">{{ orderItem.product.getPriceWithDiscount|number_format(2, ",") }}
                            €</p>
                        <p class="order-overview-item-quantity">{{ orderItem.quantity }}</p>
                        <p class="order-overview-item-total">{{ orderItem.getTotal|number_format(2, ",") }} €</p>
                    </li>
                {% endfor %}
            </ul>
        </section>
        <section class="order-section">
            <h2>Adresse de facturation</h2>
            <ul class="order-list">
                <li class="order-billing-item">
                    <p class="order-billing-item-label">Nom</p>
                    <p class="order-billing-item-value">{{ order.customer.lastName }}</p>
                </li>
                <li class="order-billing-item">
                    <p class="order-billing-item-label">Prénom</p>
                    <p class="order-billing-item-value">{{ order.customer.firstName }}</p>
                </li>
                <li class="order-billing-item">
                    <p class="order-billing-item-label">Code postal</p>
                    <p class="order-billing-item-value">{{ order.customer.postalCode }}</p>
                </li>
                <li class="order-billing-item">
                    <p class="order-billing-item-label">Ville</p>
                    <p class="order-billing-item-value">{{ order.customer.city }}</p>
                </li>
                <li class="order-billing-item">
                    <p class="order-billing-item-label">Rue</p>
                    <p class="order-billing-item-value">{{ order.customer.streetNumber }}
                        , {{ order.customer.street }}</p>
                </li>
            </ul>

            {% if app.request.attributes.get('_route') == "app_payment_failed" %}
                <a class="button button-red" href="{{ path('app_payment_index') }}">Réessayer</a>
            {% endif %}
        </section>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('paymentPage') }}
{% endblock %}